// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8qAQxWeUcbBIVyuzP2PoPUpMX6hUloI0',
    appId: '1:835533264956:web:ea031218641daab1ac4b39',
    messagingSenderId: '835533264956',
    projectId: 'mobile-game-mgm12',
    authDomain: 'mobile-game-mgm12.firebaseapp.com',
    storageBucket: 'mobile-game-mgm12.firebasestorage.app',
    measurementId: 'G-NB2SMBMZKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfuhEMqj9-kIH6-s1NOJSano2zrNCb-bE',
    appId: '1:835533264956:android:54b10b6e34821ea2ac4b39',
    messagingSenderId: '835533264956',
    projectId: 'mobile-game-mgm12',
    storageBucket: 'mobile-game-mgm12.firebasestorage.app',
  );
}
